
all: 
	make -C pcagofolo/s132/armgcc/

flash: 
	make -C pcagofolo/s132/armgcc/ $@

flash_softdevice: 
	make -C pcagofolo/s132/armgcc/ $@

erase: 
	make -C pcagofolo/s132/armgcc/ $@

clean: 
	make -C pcagofolo/s132/armgcc/ $@
